/**
 * WhatsApp Pi Extension
 *
 * Connects WhatsApp with Pi Agent using WhiskeySockets/Baileys.
 * Provides tools for the LLM to send and read messages, slash commands to
 * manage connections and QR pairing, real-time status indicators in the footer,
 * and optional auto-relay of incoming WhatsApp messages into the Pi Agent context.
 */

import * as path from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { WhatsAppClient } from "./client.ts";
import { WhatsAppStatusComponent } from "./components.ts";
import {
	formatJid,
	formatPhoneNumber,
	WhatsAppReadParamsSchema,
	WhatsAppSendParamsSchema,
	WhatsAppStatusParamsSchema,
	type WhatsAppReadParams,
	type WhatsAppRelayMode,
	type WhatsAppSendParams,
} from "./utils.ts";

export default function whatsappExtension(pi: ExtensionAPI): void {
	const authDir = path.join(process.cwd(), ".pi", "whatsapp_auth");
	const client = new WhatsAppClient(authDir);

	let currentContext: ExtensionContext | null = null;
	let relayMode: WhatsAppRelayMode = "notify";
	let lastQrShown: string | null = null;
	const sentMessageIds = new Set<string>();

	// Register flags
	pi.registerFlag("whatsapp", {
		description: "Connect to WhatsApp automatically on agent startup",
		type: "boolean",
		default: false,
	});

	pi.registerFlag("whatsapp-relay", {
		description: "Incoming WhatsApp message behavior: notify, auto, off",
		type: "string",
		default: "notify",
	});

	function getSafeContext(): ExtensionContext | null {
		if (!currentContext) return null;
		try {
			// Touch guarded property to verify context is not stale
			void currentContext.cwd;
			return currentContext;
		} catch {
			currentContext = null;
			return null;
		}
	}

	function updateStatus(ctx?: ExtensionContext): void {
		const targetCtx = ctx ?? getSafeContext();
		if (!targetCtx) return;

		try {
			const status = client.getStatus();
			if (status.status === "connected") {
				const label = status.userName || (status.userJid ? formatPhoneNumber(status.userJid) : "connected");
				targetCtx.ui.setStatus(
					"whatsapp",
					targetCtx.ui.theme.fg("success", `[WA: ${label}]`),
				);
			} else if (status.status === "connecting") {
				targetCtx.ui.setStatus(
					"whatsapp",
					targetCtx.ui.theme.fg("warning", "[WA: connecting]"),
				);
			} else if (status.status === "qr_ready") {
				targetCtx.ui.setStatus(
					"whatsapp",
					targetCtx.ui.theme.fg("warning", "[WA: scan QR]"),
				);
			} else {
				targetCtx.ui.setStatus("whatsapp", undefined);
			}
		} catch {
			currentContext = null;
		}
	}

	function safeNotify(message: string, type: "info" | "warning" | "error" = "info"): void {
		const ctx = getSafeContext();
		if (ctx) {
			try {
				ctx.ui.notify(message, type);
			} catch {
				currentContext = null;
			}
		}
	}

	function safeSendMessage(
		message: Parameters<typeof pi.sendMessage>[0],
		options?: Parameters<typeof pi.sendMessage>[1],
	): void {
		try {
			pi.sendMessage(message, options);
		} catch {
			// Ignored if session is reloading or replaced
		}
	}

	// Client event listeners
	client.on("statusChange", (_newStatus) => {
		updateStatus();
	});

	client.on("qr", (qr, _ascii) => {
		if (qr === lastQrShown) return;
		lastQrShown = qr;
		updateStatus();

		safeNotify("WhatsApp QR code generated. Run '/whatsapp qr' to scan.", "warning");

		safeSendMessage(
			{
				customType: "whatsapp-qr",
				content:
					"### WhatsApp QR Code Pairing\n" +
					"A pairing QR code was generated for your WhatsApp account.\n\n" +
					"👉 **Type `/whatsapp qr`** to open the pairing screen and scan the QR code with WhatsApp on your phone (**Settings > Linked Devices > Link a Device**).",
				display: true,
			},
			{ deliverAs: "followUp" },
		);
	});

	client.on("connected", ({ jid, name }) => {
		lastQrShown = null;
		updateStatus();

		safeNotify(`WhatsApp connected as ${name || jid}!`, "info");

		safeSendMessage(
			{
				customType: "whatsapp-status",
				content: `✅ **WhatsApp Connected Successfully!**\n- **Account:** ${name || "WhatsApp User"}\n- **JID:** \`${jid}\`\n- **Relay Mode:** \`${relayMode}\`\n\nThe agent can now send WhatsApp messages using the \`whatsapp_send\` tool.`,
				display: true,
			},
			{ deliverAs: "followUp" },
		);
	});

	client.on("disconnected", ({ isLoggedOut }) => {
		updateStatus();
		safeNotify(
			isLoggedOut ? "WhatsApp logged out. Please reconnect to pair again." : "WhatsApp disconnected.",
			isLoggedOut ? "warning" : "info",
		);
	});

	client.on("message", (msg) => {
		// Only handle messages from myself
		if (!msg.fromMe) return;

		// Ignore messages generated by this agent/extension itself
		if (sentMessageIds.has(msg.id)) return;

		const targetChat = msg.chatJid;
		const previewText = msg.text ? (msg.text.length > 60 ? `${msg.text.slice(0, 57)}...` : msg.text) : "[Media]";

		if (relayMode === "notify" || relayMode === "auto") {
			safeNotify(`WA (from me) in ${targetChat}: ${previewText}`, "info");
		}

		if (relayMode === "auto") {
			const chatType = msg.isGroup ? "Group Chat" : "Self / Direct Chat";
			safeSendMessage(
				{
					customType: "whatsapp-incoming",
					content:
						`📨 **WhatsApp Message from Yourself (${chatType}):**\n` +
						`- **Chat:** \`${msg.chatJid}\`\n` +
						`- **Type:** \`${msg.type}\`\n\n` +
						`> ${msg.text || "[No text content]"}\n\n` +
						`*To respond back to this chat, call \`whatsapp_send(to: "${msg.chatJid}", message: "...")\`.*`,
					display: true,
				},
				{ triggerTurn: true, deliverAs: "followUp" },
			);
		}
	});

	// Register LLM Tool: whatsapp_send
	pi.registerTool({
		name: "whatsapp_send",
		label: "WhatsApp Send",
		description:
			"Send a WhatsApp message (text or media attachment) directly to a WhatsApp chat JID (e.g. from an incoming message's chatJid, a group JID, or a contact JID).",
		parameters: WhatsAppSendParamsSchema,
		executionMode: "sequential",

		async execute(_toolCallId, params: WhatsAppSendParams) {
			if (!client.isConnected()) {
				return {
					content: [
						{
							type: "text",
							text: "Error: WhatsApp is not currently connected. Run '/whatsapp connect' in the terminal to link your device first.",
						},
					],
				};
			}

			if (params.mediaPath) {
				const result = await client.sendMediaMessage(params.to, params.mediaPath, params.caption || params.message);
				if (!result.success) {
					return {
						content: [{ type: "text", text: `Failed to send WhatsApp media message: ${result.error}` }],
					};
				}
				if (result.id) sentMessageIds.add(result.id);
				const target = result.toJid ?? params.to;
				return {
					content: [
						{
							type: "text",
							text: `Successfully sent media message to ${target}. Message ID: ${result.id}`,
						},
					],
				};
			}

			const result = await client.sendTextMessage(params.to, params.message);
			if (!result.success) {
				return {
					content: [{ type: "text", text: `Failed to send WhatsApp text message: ${result.error}` }],
				};
			}
			if (result.id) sentMessageIds.add(result.id);

			const target = result.toJid ?? params.to;
			return {
				content: [
					{
						type: "text",
						text: `Successfully sent WhatsApp message to ${target}. Message ID: ${result.id}`,
					},
				],
			};
		},
	});

	// Register LLM Tool: whatsapp_read
	pi.registerTool({
		name: "whatsapp_read",
		label: "WhatsApp Read",
		description:
			"Read recent WhatsApp messages (incoming and outgoing), optionally filtered by contact phone number or group chat.",
		parameters: WhatsAppReadParamsSchema,
		executionMode: "sequential",

		async execute(_toolCallId, params: WhatsAppReadParams) {
			const messages = client.getRecentMessages({
				chat: params.chat,
				limit: params.limit ?? 10,
				incomingOnly: params.incomingOnly,
			});

			if (messages.length === 0) {
				return {
					content: [
						{
							type: "text",
							text: params.chat
								? `No recent WhatsApp messages found for chat "${params.chat}".`
								: "No recent WhatsApp messages recorded in this session.",
						},
					],
				};
			}

			const formatted = messages
				.map((m) => {
					const dir = m.fromMe ? "Outgoing (Me -> Contact)" : "Incoming";
					const sender = m.senderName ? `${m.senderName} (${m.senderNumber})` : m.senderNumber;
					const time = new Date(m.timestamp).toLocaleTimeString();
					return `[${time}] ${dir} - ${sender} (${m.chatJid}):\n  ${m.text || `[${m.type}]`}`;
				})
				.join("\n\n");

			return {
				content: [
					{
						type: "text",
						text: `Recent WhatsApp Messages (${messages.length}):\n\n${formatted}`,
					},
				],
			};
		},
	});

	// Register LLM Tool: whatsapp_status
	pi.registerTool({
		name: "whatsapp_status",
		label: "WhatsApp Status",
		description: "Check the current WhatsApp connection status, logged-in user phone number, and message statistics.",
		parameters: WhatsAppStatusParamsSchema,
		executionMode: "sequential",

		async execute() {
			const status = client.getStatus();
			const connected = client.isConnected();

			return {
				content: [
					{
						type: "text",
						text:
							`WhatsApp Status:\n` +
							`- State: ${status.status}\n` +
							`- Connected: ${connected ? "Yes" : "No"}\n` +
							`- User: ${status.userName || "N/A"}\n` +
							`- User JID: ${status.userJid || "N/A"}\n` +
							`- Messages in session: ${status.messageCount}\n` +
							`- Relay mode: ${relayMode}`,
					},
				],
			};
		},
	});

	// Register LLM Tool: whatsapp_clear
	pi.registerTool({
		name: "whatsapp_clear",
		label: "WhatsApp Clear Session",
		description:
			"Clear the WhatsApp connection session, remove stored login credentials from disk, wipe session message history, and disconnect.",
		parameters: WhatsAppStatusParamsSchema,
		executionMode: "sequential",

		async execute() {
			await client.clearSession();
			sentMessageIds.clear();
			updateStatus();
			return {
				content: [
					{
						type: "text",
						text: "WhatsApp session cleared successfully. All credentials and message histories have been wiped from disk, and connection has been closed.",
					},
				],
			};
		},
	});

	// Register /whatsapp slash command
	pi.registerCommand("whatsapp", {
		description:
			"Manage WhatsApp connection and messages (usage: /whatsapp [connect|status|qr|disconnect|clear|logout|send|messages|mode])",
		handler: async (args, ctx) => {
			currentContext = ctx;
			const trimmed = args?.trim() ?? "";
			const parts = trimmed.split(/\s+/);
			const subcommand = parts[0]?.toLowerCase() || "";

			switch (subcommand) {
				case "connect": {
					if (client.isConnected()) {
						ctx.ui.notify("WhatsApp is already connected.", "info");
						return;
					}
					ctx.ui.notify("Connecting to WhatsApp via Baileys...", "info");
					await client.connect();
					updateStatus(ctx);
					break;
				}

				case "disconnect": {
					await client.disconnect();
					updateStatus(ctx);
					ctx.ui.notify("WhatsApp disconnected.", "info");
					break;
				}

				case "clear":
				case "clear-session":
				case "logout": {
					const confirmed = await ctx.ui.confirm(
						"Confirm Clear WhatsApp Session",
						"Are you sure you want to clear the WhatsApp session? This will disconnect, delete all saved login credentials from disk, and wipe message history.",
					);
					if (confirmed) {
						await client.clearSession();
						sentMessageIds.clear();
						updateStatus(ctx);
						ctx.ui.notify("WhatsApp session, credentials, and message history cleared.", "info");
					}
					break;
				}

				case "qr": {
					const qrInfo = client.getQrCode();
					if (client.isConnected()) {
						ctx.ui.notify("Already connected to WhatsApp!", "info");
						return;
					}
					if (!qrInfo.ascii) {
						if (client.getStatus().status === "disconnected") {
							ctx.ui.notify("Connecting to generate QR code...", "info");
							await client.connect();
						} else {
							ctx.ui.notify("QR code not ready yet. Please wait a moment...", "warning");
						}
					}

					if (ctx.mode === "tui") {
						await ctx.ui.custom<void>((_tui, theme, _kb, done) => {
							return new WhatsAppStatusComponent(client, theme, () => done());
						});
					} else {
						const ascii = client.getQrCode().ascii;
						if (ascii) {
							pi.sendMessage(
								{
									customType: "whatsapp-qr",
									content: `### WhatsApp QR Code:\n\`\`\`\n${ascii}\n\`\`\``,
									display: true,
								},
								{ deliverAs: "followUp" },
							);
						}
					}
					break;
				}

				case "send": {
					const recipient = parts[1];
					const messageText = parts.slice(2).join(" ");

					if (!recipient || !messageText) {
						ctx.ui.notify("Usage: /whatsapp send <chat_id> <message_text>", "warning");
						return;
					}

					const res = await client.sendTextMessage(recipient, messageText);
					if (res.success) {
						if (res.id) sentMessageIds.add(res.id);
						ctx.ui.notify(`Message sent to ${res.toJid || recipient}!`, "info");
					} else {
						ctx.ui.notify(`Failed: ${res.error}`, "error");
					}
					break;
				}

				case "messages": {
					const limitNum = parts[1] ? parseInt(parts[1], 10) : 10;
					const msgs = client.getRecentMessages({ limit: limitNum });
					if (msgs.length === 0) {
						ctx.ui.notify("No recent messages recorded.", "info");
						return;
					}

					const listStr = msgs
						.map((m) => {
							const sender = m.fromMe ? "Me" : m.senderName || m.senderNumber;
							return `• [${new Date(m.timestamp).toLocaleTimeString()}] ${sender}: ${m.text || `[${m.type}]`}`;
						})
						.join("\n");

					pi.sendMessage(
						{
							customType: "whatsapp-recent-messages",
							content: `**Recent WhatsApp Messages (${msgs.length}):**\n\n${listStr}`,
							display: true,
						},
						{ deliverAs: "followUp" },
					);
					break;
				}

				case "mode": {
					const modeArg = parts[1]?.toLowerCase();
					if (modeArg === "notify" || modeArg === "auto" || modeArg === "off") {
						relayMode = modeArg as WhatsAppRelayMode;
						ctx.ui.notify(`WhatsApp relay mode set to: ${relayMode}`, "info");
					} else {
						ctx.ui.notify("Usage: /whatsapp mode [notify|auto|off]", "warning");
					}
					break;
				}

				case "status":
				default: {
					if (ctx.mode === "tui" && !subcommand) {
						await ctx.ui.custom<void>((_tui, theme, _kb, done) => {
							return new WhatsAppStatusComponent(client, theme, () => done());
						});
					} else {
						const status = client.getStatus();
						pi.sendMessage(
							{
								customType: "whatsapp-status",
								content:
									`**WhatsApp Connection Status:**\n` +
									`- **Status:** ${status.status}\n` +
									`- **User:** ${status.userName || "N/A"} (${status.userJid || "N/A"})\n` +
									`- **Relay Mode:** \`${relayMode}\`\n` +
									`- **Message Buffer:** ${status.messageCount} messages\n` +
									`- **Commands:** \`/whatsapp connect\`, \`/whatsapp qr\`, \`/whatsapp disconnect\`, \`/whatsapp logout\``,
								display: true,
							},
							{ deliverAs: "followUp" },
						);
					}
					break;
				}
			}
		},
	});

	// Register /whatsapp-clear standalone command
	pi.registerCommand("whatsapp-clear", {
		description: "Clear WhatsApp session, wipe stored credentials, and disconnect",
		handler: async (_args, ctx) => {
			currentContext = ctx;
			const confirmed = await ctx.ui.confirm(
				"Confirm Clear WhatsApp Session",
				"Are you sure you want to clear the WhatsApp session? This will disconnect, delete all saved login credentials from disk, and wipe message history.",
			);
			if (confirmed) {
				await client.clearSession();
				sentMessageIds.clear();
				updateStatus(ctx);
				ctx.ui.notify("WhatsApp session, credentials, and message history cleared.", "info");
			}
		},
	});

	// Session lifecycle handlers
	pi.on("session_start", async (_event, ctx) => {
		currentContext = ctx;
		const autoConnect = pi.getFlag("whatsapp") === true;
		const relayFlag = pi.getFlag("whatsapp-relay");

		if (typeof relayFlag === "string" && ["notify", "auto", "off"].includes(relayFlag)) {
			relayMode = relayFlag as WhatsAppRelayMode;
		}

		if (autoConnect) {
			client.connect().catch((err) => {
				safeNotify(`WhatsApp auto-connect failed: ${err.message}`, "error");
			});
		}

		updateStatus(ctx);
	});

	pi.on("turn_start", async (_event, ctx) => {
		currentContext = ctx;
		updateStatus(ctx);
	});

	pi.on("session_before_switch", async () => {
		currentContext = null;
	});

	pi.on("session_before_fork", async () => {
		currentContext = null;
	});

	pi.on("session_before_compact", async () => {
		currentContext = null;
	});

	pi.on("session_shutdown", async () => {
		currentContext = null;
		await client.disconnect();
	});
}
